// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFMqwo1ZLO_olUunv9oqX-_t-zBYLg-04',
    appId: '1:231543446072:web:9fb719bb32af8fe31e24cd',
    messagingSenderId: '231543446072',
    projectId: 'masterfaster-de1d1',
    authDomain: 'masterfaster-de1d1.firebaseapp.com',
    storageBucket: 'masterfaster-de1d1.firebasestorage.app',
    measurementId: 'G-CN287X5PD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32a7Yvt0TytkisVCdH8BUSy7CTBalpWg',
    appId: '1:231543446072:android:9b6ef612690f38941e24cd',
    messagingSenderId: '231543446072',
    projectId: 'masterfaster-de1d1',
    storageBucket: 'masterfaster-de1d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_QPn-Z8KLiWZg-S0sm9pXNyw6z4Qo9Q',
    appId: '1:231543446072:ios:28a0aa6c9e7439701e24cd',
    messagingSenderId: '231543446072',
    projectId: 'masterfaster-de1d1',
    storageBucket: 'masterfaster-de1d1.firebasestorage.app',
    iosBundleId: 'com.example.masterfaster',
  );
}
